name: Terraform CI CD Pipeline for Deploying AWS Resources
run-name: The pipeline is triggred by ${{github.actor}} 


on: 
  push:
    branches:
          -'*'

  workflow_dispatch: # Allows maual triggering from github ui
    inputs:
      message:
        description: 'Custom message for this run'
        required: false
        default: 'The pipeline is initiated By Ansari'

env:
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}


jobs:
    build-infra:
        name: terraform-ci-cd
        runs-on: ubuntu-latest
        steps:
            - name: Custom message
              run: echo "${{ github.event.inputs.message }}"
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
            - name: Terraform Init
              id: init
              run: terraform init
              working-directory: ./Terraform-VPC
            - name: Terraform Validate
              id: validate
              run: terraform validate
              working-directory: ./Terraform-VPC
            - name: Terraform Plan
              id: plan
              run: terraform plan
              working-directory: ./Terraform-VPC
            - name: Terraform Apply
              id: apply
              run: terraform apply --auto-approve
              working-directory: ./Terraform-VPC
