name: Terraform Destroy Infrastructure

on:
  workflow_dispatch:  # This allows manual triggering from GitHub Actions UI


env:
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

  
jobs:
  destroy-infra:
    name: terraform-destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform-VPC

      - name: Terraform Destroy
        run: terraform destroy --auto-approve
        working-directory: ./Terraform-VPC
